
# NumPy basic functions


###  Five (5) basic functions in data analysis

NumPy is a python library used for working with arrays. Arrays are very frequently used in data analysis, where speed and resources are very important.

- sum 
- mean
- append
- dot
- sort


In [108]:
!pip install jovian --upgrade -q

In [109]:
import jovian

In [110]:
jovian.commit(project='NumPy basic functions')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "math-nights/NumPy basic functions"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [111]:
import numpy as np

In [112]:
# List of functions explained 
function1 = np.sum 
function2 = np.mean
function3 = np.append
function4 = np.dot
function5 = np.sort

## Function 1 - numpy.sum() 

This function returns the sum of array elements over the specified axis, the sum of all elements, the sum of each row, and the sum of each column of a given array.

In [113]:
# Example 1 - working 
arr = np.array([[1, 2], 
               [3, 4]]) 

total = np.sum(arr)

print(f'Sum of all array elements: {total}')

Sum of all array elements: 10


We have passed the array 'arr' and axis=0 in the function, the sum of the column elements has been calculated accordingly.

In [114]:
# Example 2 - working
arr = np.array([[1, 2], 
               [3, 4]])

total = np.sum(arr, axis=0)

print(f'Sum of the column elements: {total}')

Sum of the column elements: [4 6]


Axis Error

In [115]:
# Example 3 - breaking 
arr1 = np.array([[1, 2], 
                [3, 4]])

arr2 = np.array([[5, 6], 
                [7, 8]])

total = np.sum((arr1, arr2), axis=3)

print(f'Sum of arr1 & arr2 elements: {total}')

AxisError: axis 3 is out of bounds for array of dimension 3

AxisError: axis 3 is out of bounds. So we should choose axis = 0, 1 or 2. Or we can only write np.sum((arr1, arr2)) for the sum of all  arr1 & arr2 elements.

In data analysis, the sum function is a very useful tool. If we specify the axis value, the sum of elements along that axis is returned. If the array shape is (X, Y) then the sum along 0-axis will be of shape (1, Y). The sum along 1-axis will be of shape (1, X). 

In [116]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/numpy-basic-functions" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'

## Function 2 - numpy.mean()

Mean is The average value. The numpy.mean() function is used to compute the arithmetic mean along the specified axis (the arithmetic mean is the sum of elements, along with an axis divided by the number of elements)

In [117]:
# Example 1 - working
grades = [10, 5, 17, 2, 12, 19.5, 7.5, 13.75, 14.25, 11.5, 6.5, 16.75, 9.25]

mean = np.mean(grades)

print(f'Mean of all grades: {mean}')

Mean of all grades: 11.153846153846153


We have created two arrays 'region1' and 'region2' using np.array() function, and two variables 'a' and 'b' using np.mean(). To compare the mean of temperature between the first and second regions.

In [118]:
# Example 2 - working
region1 = [10, 13, 25, 45, 50, 12, 14, 6, 14, 24, 35, 16.5]

region2 = [5, 7, 4, 12, 25, 7.5, 16.25, 10, 12.75, 12, 3, 2]

a = np.mean(region1)
b = np.mean(region2)

print(f'Mean of temperature in first region was {a} but in second region was {b}')

Mean of temperature in first region was 22.041666666666668 but in second region was 9.708333333333334


The student was absent so we try to type 'None' instead of '00' mark.

In [119]:
# Example 3 - breaking 
grades = [10, 5, 17, 2, None, 19.5, 7.5, 13.75, 14.25, 11.5, 6.5, 16.75, 9.25]

x = np.mean(grades)

print(f'Mean of all grades: {x}')

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

TypeError:'int' and 'NoneType'. We should type only numbers.

In Machine Learning (and in mathematics) the mean value is very important.

In [121]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/numpy-basic-functions" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'

## Function 3 - numpy.append()

Append means adding something. The numpy.append() function is used to add or append new values to an existing numpy array. This function adds the new values at the end of the array.

In [122]:
# Example 1 - working
arr1 = np.array(['Saturday', 'Sunday', 'Monday'])

arr2 = np.array(['Tuesday', 'Wednesday', 'Thursday', 'Friday'])

days = np.append(arr1, arr2)

print(f'weekdays: {days}')

weekdays: ['Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday' 'Thursday' 'Friday']


 Append different values: strings, numbers,...

In [123]:
# Example 2 - working
a = np.array(['One', 'Two', 'Three'])

b = np.array([1, 2, 3])

c = np.append(a, b)

print(f'Result: {c}')

Result: ['One' 'Two' 'Three' '1' '2' '3']


Append three arrays

In [124]:
# Example 3 - breaking 
a = np.array(['One', 'Two', 'Three'])

b = np.array([[1, 2, 3, 2020],
              ['four', 'five', 'six', 'seven']])

c = np.array([8, 9, 10])

d = np.append(a, b, c)

print(f'Result: {d}')

TypeError: only integer scalar arrays can be converted to a scalar index

The numpy append() function is used to merge two arrays.

It's a very useful tool to append large arrays fastly.

In [125]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/numpy-basic-functions" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'

## Function 4 - numpy.dot()

 A function performs the dot product of two arrays.

In [126]:
# Example 1 - working
a = np.array([[1, 2, 3], 
             [5, 6, 7], 
             [9, 10, 11]])

b = np.array([[10, 20, 30], 
             [50, 60, 70], 
             [90, 100, 110]])

c = np.dot(a, b)

print(f'The dot product of the two arrays:')
print(c)

The dot product of the two arrays:
[[ 380  440  500]
 [ 980 1160 1340]
 [1580 1880 2180]]


The dot product of the temperature in two regions

In [127]:
# Example 2 - working
region1 = [10, 13, 25, 45, 50, 12, 14, 6, 14, 24, 35, 16.5]

region2 = [5, 7, 4, 12, 25, 7.5, 16.25, 10, 12.75, 12, 3, 2]

d = np.dot(region1, region2)

print(f'The dot product of the temperature in the two regions:')

print(d)


The dot product of the temperature in the two regions:
3013.0


If 'a' is 3-dimensional array and 'b' is 4-dimensional array

In [128]:
# Example 3 - breaking 
a = np.array([[1, 2, 3], 
             [5, 6, 7], 
             [9, 10, 11]])

b = np.array([[10, 20, 30, 40], 
             [50, 60, 70, 80],
             [90, 100, 200, 300],
             [400, 540, 750, 230]])

c = np.dot(a, b)

print(f'The dot product of the two arrays:')
print(c)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

ValueError: shapes (3,3) and (4,4) not aligned. So they must have the same shape.

In " Linear Algebra " dot product is a very helpful tool.

In [129]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/numpy-basic-functions" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'

## Function 5 - numpy.sort()

This function gives a sorted copy of the source array or input array.

In [130]:
# Example 1 - working
x = np.array([ 1, 4, 11, 6, 12, 3, 7, 9, 2, 5, 8, 10])
             
s = np.sort(x)

print(f'A sorted copy of the array: {s}')


A sorted copy of the array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


Shows a sorted copy of the source array of the same type and different shape.

In [131]:
# Example 2 - working
x = np.array([[4,7,12,10],
              [9,2,8,6],
              [5,11,3,1]]) 


s = np.sort(x)
y = np.sort(x, axis=None)

print(f'A sorted copy of the source array:')
print(s)
print(f'A sorted copy of the source array in different shapee:')
print(y)


A sorted copy of the source array:
[[ 4  7 10 12]
 [ 2  6  8  9]
 [ 1  3  5 11]]
A sorted copy of the source array in different shapee:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Shows a sorted copy of the source array of the same type and different axis

In [132]:
# Example 3 - breaking 
x = np.array([[4,7,12,10],
              [9,2,8,6],
              [5,11,3,1]]) 


s = np.sort(x)
y = np.sort(x, axis=2)

print(f'A sorted copy of the source array:')
print(s)
print(f'A sorted copy of the source array in different shapee:')
print(y)

AxisError: axis 2 is out of bounds for array of dimension 2

AxisError: axis 2 is out of bounds for array of dimension 2. We must choose the axis in the bounds of the array, it should be 0 or 1.

Putting elements in a ordered sequence is a very useful tool in data analysis.

In [133]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/numpy-basic-functions" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'

## Conclusion

My NumPy basic functions report provides five (5) basic functions in data analysis. My NumPy report is designed for absolute beginners.

## Reference Links

* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Javatpoint : https://www.javatpoint.com/numpy-tutorial
* w3schools : https://www.w3schools.com/python/numpy_intro.asp

In [134]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "math-nights/numpy-basic-functions" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/math-nights/numpy-basic-functions


'https://jovian.ml/math-nights/numpy-basic-functions'